const COMPILED_BATCH_HARNESS_SCRIPT = [
  '#!/bin/sh',
  'set -u',
  '',
  'tests_file="$1"',
  'lang="$2"',
  'workdir="$3"',
  'fail_fast="$4"',
  '',
  'BASE64_SUPPORTS_WRAP=0',
  'if printf "" | base64 -w 0 >/dev/null 2>&1; then',
  '  BASE64_SUPPORTS_WRAP=1',
  'fi',
  '',
  'BASE64_DECODE_FLAG="-D"',
  'if printf "" | base64 -d >/dev/null 2>&1; then',
  '  BASE64_DECODE_FLAG="-d"',
  'fi',
  '',
  'TIMEOUT_CMD="timeout"',
  'if ! command -v "$TIMEOUT_CMD" >/dev/null 2>&1; then',
  '  if command -v gtimeout >/dev/null 2>&1; then',
  '    TIMEOUT_CMD="gtimeout"',
  '  else',
  '    TIMEOUT_CMD=""',
  '  fi',
  'fi',
  '',
  'decode_b64() {',
  '  if [ -z "${1:-}" ]; then',
  '    return 0',
  '  fi',
  '  printf \'%s\' "$1" | base64 "$BASE64_DECODE_FLAG" 2>/dev/null',
  '}',
  '',
  'encode_b64() {',
  '  if [ "$BASE64_SUPPORTS_WRAP" -eq 1 ]; then',
  '    printf \'%s\' "$1" | base64 -w 0',
  '  else',
  '    printf \'%s\' "$1" | base64 | tr -d "\\n"',
  '  fi',
  '}',
  '',
  'run_with_timeout() {',
  '  timeout_sec="$1"',
  '  shift',
  '  if [ -n "$TIMEOUT_CMD" ]; then',
  '    "$TIMEOUT_CMD" "$timeout_sec" "$@"',
  '  else',
  '    "$@"',
  '  fi',
  '}',
  '',
  'normalize_text() {',
  '  printf \'%s\' "$1" | sed "s/[[:space:]]*$//"',
  '}',
  '',
  'main_class=""',
  'python_entry="$workdir/code.py"',
  'if [ "$lang" = "java" ]; then',
  '  main_class=$(grep -l "public static void main" "$workdir"/*.java 2>/dev/null | head -n1 | xargs basename -s .java 2>/dev/null || true)',
  '  if [ -z "$main_class" ]; then',
  '    main_class=$(ls "$workdir"/*.class 2>/dev/null | head -n1 | xargs basename -s .class 2>/dev/null || true)',
  '  fi',
  'elif [ "$lang" = "python" ]; then',
  '  pyc_entry=$(ls "$workdir"/__pycache__/code.*.pyc 2>/dev/null | head -n1 || true)',
  '  if [ -n "$pyc_entry" ]; then',
  '    python_entry="$pyc_entry"',
  '  fi',
  'fi',
  '',
  'while IFS="$(printf \'\\t\')" read -r tc_id tc_hidden tc_time tc_expected_b64 tc_input_b64 || [ -n "${tc_id:-}" ]; do',
  '  if [ -z "${tc_id:-}" ]; then',
  '    continue',
  '  fi',
  '',
  '  input_text=$(decode_b64 "$tc_input_b64")',
  '  expected_text=$(decode_b64 "$tc_expected_b64")',
  '  timeout_sec=$(( (tc_time + 999) / 1000 ))',
  '  if [ "$timeout_sec" -lt 1 ]; then',
  '    timeout_sec=1',
  '  fi',
  '',
  '  stderr_file="$workdir/stderr_${tc_id}.txt"',
  '  rm -f "$stderr_file"',
  '',
  '  start_s=$(date +%s)',
  '  if [ "$lang" = "c" ]; then',
  '    stdout_text=$(printf \'%s\' "$input_text" | run_with_timeout "$timeout_sec" "$workdir/a.out" 2>"$stderr_file")',
  '    exit_code=$?',
  '  elif [ "$lang" = "java" ]; then',
  '    stdout_text=$(printf \'%s\' "$input_text" | run_with_timeout "$timeout_sec" java -cp "$workdir" "$main_class" 2>"$stderr_file")',
  '    exit_code=$?',
  '  else',
  '    stdout_text=$(printf \'%s\' "$input_text" | run_with_timeout "$timeout_sec" python3 "$python_entry" 2>"$stderr_file")',
  '    exit_code=$?',
  '  fi',
  '  end_s=$(date +%s)',
  '  time_ms=$(( (end_s - start_s) * 1000 ))',
  '  stderr_text=$(cat "$stderr_file" 2>/dev/null || true)',
  '',
  '  status="passed"',
  '  if [ "$exit_code" -eq 124 ]; then',
  '    status="time_limit_exceeded"',
  '    stderr_text="timed out"',
  '  elif [ "$exit_code" -ne 0 ]; then',
  '    status="runtime_error"',
  '  else',
  '    out_norm=$(normalize_text "$stdout_text")',
  '    exp_norm=$(normalize_text "$expected_text")',
  '    if [ "$out_norm" != "$exp_norm" ]; then',
  '      status="failed"',
  '    fi',
  '  fi',
  '',
  '  stdout_b64=$(encode_b64 "$stdout_text")',
  '  stderr_b64=$(encode_b64 "$stderr_text")',
  '',
  '  echo "__RESULT__${tc_id}|${exit_code}|${status}|${tc_hidden}|${time_ms}|${stdout_b64}|${stderr_b64}"',
  '',
  '  if [ "$fail_fast" = "1" ] && [ "$status" != "passed" ]; then',
  '    break',
  '  fi',
  'done < "$tests_file"',
].join('\n');

function buildHarnessTsvTestsPayload(batch) {
  return batch
    .map((tc) => {
      const expectedB64 = Buffer.from(tc.expectedOutput ?? '').toString(
        'base64'
      );
      const inputB64 = Buffer.from(tc.stdinInput ?? tc.input ?? '').toString(
        'base64'
      );
      return `${tc.id}\t${tc.is_hidden ? 1 : 0}\t${tc.time_limit_ms ?? 2000}\t${expectedB64}\t${inputB64}`;
    })
    .join('\n');
}

module.exports = {
  COMPILED_BATCH_HARNESS_SCRIPT,
  buildHarnessTsvTestsPayload,
};
