/**
 * Shell batch harness for running multiple test cases inside a Docker container.
 *
 * Protocol: each test case emits a line:
 *   __RESULT__<id>|<exitCode>|<status>|<hidden>|<time_ms>|<memory_kb>|<stdout_b64>|<stderr_b64>
 *
 * Time is measured in milliseconds using nanosecond-precision `date +%s%N`
 * (falls back to second-precision `date +%s` if %N not supported).
 *
 * Memory is captured via /usr/bin/time -v (GNU time) → "Maximum resident set size"
 * which gives kilobytes on Linux. Falls back to 0 if not available.
 */

const COMPILED_BATCH_HARNESS_SCRIPT = [
  '#!/bin/sh',
  'set -u',
  '',
  'tests_file="$1"',
  'lang="$2"',
  'workdir="$3"',
  'fail_fast="$4"',
  '',
  '# ── Base64 portability ──────────────────────────────────────────────',
  'BASE64_SUPPORTS_WRAP=0',
  'if printf "" | base64 -w 0 >/dev/null 2>&1; then',
  '  BASE64_SUPPORTS_WRAP=1',
  'fi',
  '',
  'BASE64_DECODE_FLAG="-D"',
  'if printf "" | base64 -d >/dev/null 2>&1; then',
  '  BASE64_DECODE_FLAG="-d"',
  'fi',
  '',
  '# ── Timeout command detection ───────────────────────────────────────',
  'TIMEOUT_CMD="timeout"',
  'if ! command -v "$TIMEOUT_CMD" >/dev/null 2>&1; then',
  '  if command -v gtimeout >/dev/null 2>&1; then',
  '    TIMEOUT_CMD="gtimeout"',
  '  else',
  '    TIMEOUT_CMD=""',
  '  fi',
  'fi',
  '',
  '# ── GNU time detection (for memory measurement) ────────────────────',
  'GNU_TIME=""',
  'if command -v /usr/bin/time >/dev/null 2>&1; then',
  '  if /usr/bin/time -v true 2>/dev/null; then',
  '    GNU_TIME="/usr/bin/time -v"',
  '  fi',
  'fi',
  '',
  '# ── Nanosecond time support detection ──────────────────────────────',
  'HAS_NANO=0',
  'test_ns=$(date +%s%N 2>/dev/null || true)',
  'case "$test_ns" in',
  '  *N) HAS_NANO=0 ;;  # %N not supported (outputs literal N)',
  '  *[0-9]) HAS_NANO=1 ;;',
  'esac',
  '',
  'get_time_ns() {',
  '  if [ "$HAS_NANO" -eq 1 ]; then',
  '    date +%s%N',
  '  else',
  '    # Fallback: seconds * 1_000_000_000',
  '    echo "$(date +%s)000000000"',
  '  fi',
  '}',
  '',
  'decode_b64() {',
  '  if [ -z "${1:-}" ]; then',
  '    return 0',
  '  fi',
  '  printf \'%s\' "$1" | base64 "$BASE64_DECODE_FLAG" 2>/dev/null',
  '}',
  '',
  'encode_b64() {',
  '  if [ "$BASE64_SUPPORTS_WRAP" -eq 1 ]; then',
  '    printf \'%s\' "$1" | base64 -w 0',
  '  else',
  '    printf \'%s\' "$1" | base64 | tr -d "\\n"',
  '  fi',
  '}',
  '',
  'run_with_timeout() {',
  '  timeout_sec="$1"',
  '  shift',
  '  if [ -n "$TIMEOUT_CMD" ]; then',
  '    "$TIMEOUT_CMD" "$timeout_sec" "$@"',
  '  else',
  '    "$@"',
  '  fi',
  '}',
  '',
  'normalize_text() {',
  '  printf \'%s\' "$1" | sed "s/[[:space:]]*$//"',
  '}',
  '',
  '# ── Language-specific setup ────────────────────────────────────────',
  'main_class=""',
  'python_entry="$workdir/code.py"',
  'if [ "$lang" = "java" ]; then',
  '  if [ -f "$workdir/main_class.txt" ]; then',
  '    main_class=$(cat "$workdir/main_class.txt" 2>/dev/null || true)',
  '  fi',
  '  if [ -z "$main_class" ]; then',
  '  main_class=$(grep -l "public static void main" "$workdir"/*.java 2>/dev/null | head -n1 | xargs basename -s .java 2>/dev/null || true)',
  '  fi',
  '  if [ -z "$main_class" ]; then',
  '    main_class=$(ls "$workdir"/*.class 2>/dev/null | head -n1 | xargs basename -s .class 2>/dev/null || true)',
  '  fi',
  'elif [ "$lang" = "python" ]; then',
  '  pyc_entry=$(ls "$workdir"/__pycache__/code.*.pyc 2>/dev/null | head -n1 || true)',
  '  if [ -n "$pyc_entry" ]; then',
  '    python_entry="$pyc_entry"',
  '  fi',
  'fi',
  '',
  '# ── Main test loop ─────────────────────────────────────────────────',
  'while IFS="$(printf \'\\t\')" read -r tc_id tc_hidden tc_time tc_expected_b64 tc_input_b64 || [ -n "${tc_id:-}" ]; do',
  '  if [ -z "${tc_id:-}" ]; then',
  '    continue',
  '  fi',
  '',
  '  input_text=$(decode_b64 "$tc_input_b64")',
  '  expected_text=$(decode_b64 "$tc_expected_b64")',
  '  timeout_sec=$(( (tc_time + 999) / 1000 ))',
  '  if [ "$timeout_sec" -lt 1 ]; then',
  '    timeout_sec=1',
  '  fi',
  '',
  '  stderr_file="$workdir/stderr_${tc_id}.txt"',
  '  time_file="$workdir/time_${tc_id}.txt"',
  '  rm -f "$stderr_file" "$time_file"',
  '',
  '  memory_kb=0',
  '  start_ns=$(get_time_ns)',
  '',
  '  # Build the actual execution command',
  '  if [ "$lang" = "c" ]; then',
  '    run_target="$workdir/a.out"',
  '  elif [ "$lang" = "java" ]; then',
  '    run_target="java -cp $workdir $main_class"',
  '  else',
  '    run_target="python3 $python_entry"',
  '  fi',
  '',
  '  # Execute with optional GNU time for memory measurement',
  '  if [ -n "$GNU_TIME" ]; then',
  '    stdout_text=$(printf \'%s\' "$input_text" | run_with_timeout "$timeout_sec" $GNU_TIME sh -c "$run_target" 2>"$stderr_file")',
  '    exit_code=$?',
  '    # Extract peak RSS from GNU time verbose output',
  '    mem_line=$(grep "Maximum resident set size" "$stderr_file" 2>/dev/null || true)',
  '    if [ -n "$mem_line" ]; then',
  '      memory_kb=$(echo "$mem_line" | grep -o "[0-9]*" | tail -1)',
  '      # Remove GNU time output from stderr (keep only program stderr)',
  '      sed -i "/Command being timed/d;/User time/d;/System time/d;/Percent of CPU/d;/Elapsed/d;/Average shared/d;/Average unshared/d;/Average stack/d;/Average total/d;/Maximum resident/d;/Average resident/d;/Major/d;/Minor/d;/Voluntary/d;/Involuntary/d;/Swaps/d;/File system/d;/Socket/d;/Signals/d;/Page size/d;/Exit status/d" "$stderr_file" 2>/dev/null || true',
  '    fi',
  '  else',
  '    if [ "$lang" = "c" ]; then',
  '      stdout_text=$(printf \'%s\' "$input_text" | run_with_timeout "$timeout_sec" "$workdir/a.out" 2>"$stderr_file")',
  '      exit_code=$?',
  '    elif [ "$lang" = "java" ]; then',
  '      stdout_text=$(printf \'%s\' "$input_text" | run_with_timeout "$timeout_sec" java -cp "$workdir" "$main_class" 2>"$stderr_file")',
  '      exit_code=$?',
  '    else',
  '      stdout_text=$(printf \'%s\' "$input_text" | run_with_timeout "$timeout_sec" python3 "$python_entry" 2>"$stderr_file")',
  '      exit_code=$?',
  '    fi',
  '  fi',
  '',
  '  end_ns=$(get_time_ns)',
  '  time_ms=$(( (end_ns - start_ns) / 1000000 ))',
  '  if [ "$time_ms" -lt 0 ]; then time_ms=0; fi',
  '',
  '  stderr_text=$(cat "$stderr_file" 2>/dev/null || true)',
  '',
  '  # ── Verdict determination (exit-code-first) ──────────────────────',
  '  status="passed"',
  '  if [ "$exit_code" -eq 124 ]; then',
  '    status="time_limit_exceeded"',
  '    stderr_text="Time limit exceeded (${timeout_sec}s)"',
  '  elif [ "$exit_code" -eq 137 ]; then',
  '    status="memory_limit_exceeded"',
  '    stderr_text="Memory limit exceeded (killed by OOM)"',
  '  elif [ "$exit_code" -ne 0 ]; then',
  '    status="runtime_error"',
  '  else',
  '    out_norm=$(normalize_text "$stdout_text")',
  '    exp_norm=$(normalize_text "$expected_text")',
  '    if [ "$out_norm" != "$exp_norm" ]; then',
  '      status="wrong_answer"',
  '    fi',
  '  fi',
  '',
  '  stdout_b64=$(encode_b64 "$stdout_text")',
  '  stderr_b64=$(encode_b64 "$stderr_text")',
  '',
  '  # 8-field protocol: id|exitCode|status|hidden|time_ms|memory_kb|stdout_b64|stderr_b64',
  '  echo "__RESULT__${tc_id}|${exit_code}|${status}|${tc_hidden}|${time_ms}|${memory_kb}|${stdout_b64}|${stderr_b64}"',
  '',
  '  if [ "$fail_fast" = "1" ] && [ "$status" != "passed" ]; then',
  '    break',
  '  fi',
  'done < "$tests_file"',
].join('\n');

function buildHarnessTsvTestsPayload(batch) {
  return batch
    .map((tc) => {
      const expectedB64 = Buffer.from(tc.expectedOutput ?? '').toString(
        'base64'
      );
      const inputB64 = Buffer.from(tc.stdinInput ?? tc.input ?? '').toString(
        'base64'
      );
      return `${tc.id}\t${tc.is_hidden ? 1 : 0}\t${tc.time_limit_ms ?? 2000}\t${expectedB64}\t${inputB64}`;
    })
    .join('\n');
}

module.exports = {
  COMPILED_BATCH_HARNESS_SCRIPT,
  buildHarnessTsvTestsPayload,
};
