// utils/ClientPdf.ts
import { jsPDF } from "jspdf";

export async function generatePdfClient({
  studentName,
  rollNumber,
  practicalTitle,
  code,
  language,
  submissionDate,
  status,
  marks,
  filename = "submission_report.pdf",
}: {
  studentName: string;
  rollNumber: string;
  practicalTitle: string;
  code: string;
  language: string;
  submissionDate: string;
  status: string;
  marks?: number;
  filename?: string;
}) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const marginLeft = 40;
  const marginTop = 40;
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const usableWidth = pageWidth - marginLeft * 2;

  const headingFontSize = 18;
  const subHeadingFontSize = 14;
  const textFontSize = 11;
  const monoFont = "courier";

  let cursorY = marginTop;

  const newPage = () => {
    doc.addPage();
    cursorY = marginTop;
  };

  // Header Section
  doc.setFont("helvetica", "bold");
  doc.setFontSize(headingFontSize);
  doc.setTextColor(63, 81, 181); // Indigo color
  doc.text("Practical Submission Report", marginLeft, cursorY);
  cursorY += headingFontSize + 20;

  // Student Details
  doc.setDrawColor(200);
  doc.setLineWidth(1);
  doc.line(marginLeft, cursorY - 10, pageWidth - marginLeft, cursorY - 10);

  doc.setTextColor(0);
  doc.setFontSize(textFontSize);

  const drawField = (label: string, value: string, xOffset: number = 0) => {
    doc.setFont("helvetica", "bold");
    doc.text(`${label}:`, marginLeft + xOffset, cursorY);
    doc.setFont("helvetica", "normal");
    doc.text(value, marginLeft + xOffset + doc.getTextWidth(`${label}: `), cursorY);
  };

  drawField("Student", studentName);
  drawField("Roll No", rollNumber, 250);
  cursorY += 20;

  drawField("Practical", practicalTitle);
  cursorY += 20;

  drawField("Submitted", submissionDate);
  drawField("Language", language, 250);
  cursorY += 20;

  drawField("Status", status.toUpperCase());
  if (marks !== undefined) {
    drawField("Marks", marks.toString(), 250);
  }
  cursorY += 30;

  // Code Section
  doc.setDrawColor(230);
  doc.setFillColor(248, 250, 252); // Light gray background
  doc.rect(marginLeft, cursorY - 15, usableWidth, 25, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(subHeadingFontSize);
  doc.setTextColor(30);
  doc.text("Source Code", marginLeft + 10, cursorY + 2);
  cursorY += 25;

  doc.setFont(monoFont, "normal");
  doc.setFontSize(10);
  doc.setTextColor(0);

  const lines = doc.splitTextToSize(code || "No code submitted", usableWidth);
  const lineHeight = 14;

  lines.forEach((line: string) => {
    if (cursorY + lineHeight > pageHeight - marginTop) {
      newPage();
      doc.setFont(monoFont, "normal");
      doc.setFontSize(10);
    }
    doc.text(line, marginLeft, cursorY);
    cursorY += lineHeight;
  });

  // Footer (on all pages if needed, but simple one at end for now)
  const totalPages = doc.internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(9);
    doc.setTextColor(150);
    doc.text(`Page ${i} of ${totalPages}`, pageWidth - marginLeft - 50, pageHeight - 20);
    doc.text("Generated by CodeGuard", marginLeft, pageHeight - 20);
  }

  doc.save(filename);
}
